# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acd4764f69cffa7776407841786954dfb3c52e046554c3a9e0bcdef2afd0a9aa29af3f008bbaa04b4192392dbe94f6cac8c4a3c490a8256ce1add73e9329603f

test:
  secret_key_base: 1babc72b92eaf8140b04b1f64583f58c9fe127bd28711305e7f049e6afeeb6a0aaa1de479916a8aa0c2748df3a08163c512fa5d86de6b69d999a3447d3ad6731

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
